name: All Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            target: thumbv7em-none-eabihf
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Check code formatting
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --verbose --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and check documentation
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose