name: All Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            target: thumbv7em-none-eabihf
            override: true
      - uses: actions-rs/clippy-check@v1
        name: Run clippy with no optional features
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --lib --examples --target thumbv7em-none-eabihf -- -D warnings
      - uses: actions-rs/clippy-check@v1
        name: Run clippy with the 'byob' feature
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --lib --examples --target thumbv7em-none-eabihf --features byob -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
            command: fmt
            args: --verbose --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and check documentation examples
        run: make test

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: thumbv7em-none-eabihf
            override: true
      - name: Make examples
        run: make examples